sudo: false
dist: trusty
language: node_js
node_js:
  - "6"
script: npm run coveralls
cache:
  directories:
  - node_modules
  - typings/globals
after_success:
  - npm run deploy
  - npm install typings -g
  - typings install
  - npm run build
deploy:
  provider: script
  script: scripts/prod-deploy.sh
  skip_cleanup: true
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^(prod|dev)-.*$"
env:
  global:
    secure: VzOTf/fa/FMCvQI92L9dAksiHlJ/IZenwd2vEiG0JnmBxMRZCqkJn00xKMinA014dOk/gMoQaTymQ6ZdC2dDI9pBcdmEUMIRtXpBMSCecgPZq+kpS1Uk6YqXcCDcOAphtAgP53NHLqjoIFq9LgT4mDJmTJOd0I3khCIU3njViBs74enbc2yy0EGAGcQ/jfZvvSFIXaOS/eaS7LE/Xct1Y6aucp+JBabmmTDSv1e4CXbpiHp0oKU9yvTpEYI7tDe9TXJD70zGOGjeQfJt6fyhqsW5V+oXjubMeKkqiTUbwN7u4BgeLqSsNSUfP9guJO2zDGCv9vxXQn1XdIZWcEmO2W35mpvHURkQ43QpHIkJvBqx25fK/s6riFTdisfdQQ7KsG/+JL6xEd0Plisjy85EbIzqqMh7XyJ5bMRIHALxsG2rGXy4QlTmsyqKEZipXxiklWsE/duxrXmbazqhUwOwNjpe3uN4sUa0yFEgqvoC+CygYC7ZqZ5SNkRt/wiR8AVaNwIoqNS43he30C3xnA6hHCJvaQ0uhZ+lOOxhYltFfNImO4kmVDvWt+dGN+qsJ7+/KwSALeQCmzYo0fumkbBZHL2Q9jTlANLmwX86fqjahfhGRHshORoOFJ7I+Z6D2KE4iXfmebakzy693/85y/6vmJEcj7TvPRRPg6GhxyXbc/4=
