sudo: false
dist: trusty
language: node_js
node_js:
- '6'
script: npm run coveralls
cache:
  directories:
  - node_modules
  - typings/globals
after_success:
- npm run deploy
- npm install typings -g
- typings install
- npm run build
deploy:
  provider: script
  script: scripts/prod-deploy.sh
  skip_cleanup: true
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^(prod|dev)-.*$"
env:
  global:
    secure: ja1pnmFdRN/CUxhvBCWretIfvN5dJos4PgahLI+KQj4ubjBU2NetwDDX+AcPNNTunUvDAET7LnMY3+NVj1WiftYyeio4oSW4u4rRa66sRqrzmPpexu99JTN2msxY0Qv+S97bYw0h1zJ/39/ulyekV1H6Qel6M/HUSZh8I7Ay+ViaQf0KsHvLyhqlEsDhNhH7VnD7dH3OtJ3WmH8pYV9fxsDzeojtlcnhrWiq25Z3HD+OqWNxfx9Y6ZXl6/o7GHkDmsLhkwf4F9oSUN38qIG98lzPDNCUagTwzPDZpvhIbif6canlHjVeKgE6IMoE7722G9FDScTk1Ws65fvjuYmI/RI9rZ6SKtcPo2Fx1esd2en/r2Dy0Zi8nJcDC/gxhxQxROEYox/xC+m4gXN+lG+M4BbodJIj3rYz5jsjvFSrIJpVXXspBQyRyqYFsfJrFOgGslyJ3YGZcay9ynlx14V00Ad2UotTWYSBZB7dZ/0kAqDrUgd3YSZpFiL1iKB6D95I0MLGsGoPLu2Alob02mkirSTxU3h/qyD6qqhs6N3GIBqZrCYYm6Bn4dL3AnQm74G6gXOpYMV8XOv5Pg9pX1TvgMDUqFY/3i5d1QE1j6I9xdSSFPf/x/8mWWLQE+f3dp1c2ZIr280k8k0pDPdozImJeHdeORnxQAQioQSFw85v+uU=
